event_inherited();
//Weapon Stats
damage = 1;
maxAmmo = 75;
currentAmmo = maxAmmo;
reloading = false;
reloadSpeed = 45;
pelletCount = 1;
pelletSpread = 1;
pelletSpeed = 10;
pelletSpeedVariance = 0.75;
pelletLifetime = 15;
pelletExplosive = false;
pelletExplosiveRadius = 64;
ammo = objFlamethrowerProjectile;
fully_automatic = true;
fire_sound = snd_flamerthrower;
ammo_ui_sprite = spr_ui_flamethrower_tank;
ammo_ui_per_sprite = 75;
fire_rate = 3;